'use client';

import type { RentBill } from '@/types/rentBill';
import Image from 'next/image';

export type ReceiptLanguage = 'bn' | 'en';

const copy = {
  en: {
    title: 'Monthly Rent Receipt',
    receiptNumber: 'Receipt No.',
    billedTo: 'Billed to',
    property: 'Property',
    description: 'Description',
    amount: 'Amount',
    subtotal: 'Subtotal',
    adjustment: 'Adjustment',
    grandTotal: 'Grand Total',
    issued: 'Issued',
    dueDate: 'Due date',
    paidDate: 'Paid date',
    unpaid: 'Unpaid',
    paymentNote: 'Payment note',
    generatedBy: 'Generated by AHB Home Management System',
    statuses: { due: 'DUE', paid: 'PAID', void: 'VOID' },
  },
  bn: {
    title: 'মাসিক বাড়ি ভাড়ার রশিদ',
    receiptNumber: 'রশিদ নং',
    billedTo: 'ভাড়াটিয়া',
    property: 'সম্পত্তি',
    description: 'বিবরণ',
    amount: 'পরিমাণ',
    subtotal: 'উপমোট',
    adjustment: 'সমন্বয়',
    grandTotal: 'সর্বমোট',
    issued: 'ইস্যুর তারিখ',
    dueDate: 'পরিশোধের শেষ তারিখ',
    paidDate: 'পরিশোধের তারিখ',
    unpaid: 'অপরিশোধিত',
    paymentNote: 'পেমেন্ট নোট',
    generatedBy: 'AHB Home Management System দ্বারা তৈরি',
    statuses: { due: 'বকেয়া', paid: 'পরিশোধিত', void: 'বাতিল' },
  },
} as const;

const bengaliItemLabels: Record<string, string> = {
  BASE_RENT: 'মূল ভাড়া',
  ELECTRICITY: 'বিদ্যুৎ বিল',
  WATER: 'পানি বিল',
  GAS: 'গ্যাস বিল',
  MAINTENANCE: 'রক্ষণাবেক্ষণ / সার্ভিস চার্জ',
  GARBAGE_CLEANING: 'ময়লা পরিষ্কারের বিল',
  CARETAKER: 'দারোয়ানের বিল',
  STAIRCASE_CLEANING: 'সিঁড়ি পরিষ্কারের বিল',
  COMMON_ELECTRICITY_LIFT: 'কমন বিদ্যুৎ / লিফট বিল',
  PARKING: 'পার্কিং বিল',
  INTERNET: 'ইন্টারনেট বিল',
  OTHER: 'অন্যান্য বিল',
};

const formatMoney = (value: number, language: ReceiptLanguage) => {
  const locale = language === 'bn' ? 'bn-BD' : 'en-BD';

  return `৳${new Intl.NumberFormat(locale, {
    minimumFractionDigits: 0,
    maximumFractionDigits: 2,
  }).format(value)}`;
};

const formatDate = (
  value: string | null | undefined,
  language: ReceiptLanguage,
) => {
  if (!value) return '—';

  return new Intl.DateTimeFormat(language === 'bn' ? 'bn-BD' : 'en-GB', {
    day: '2-digit',
    month: 'long',
    year: 'numeric',
  }).format(new Date(value));
};

const formatMonth = (period: string, language: ReceiptLanguage) => {
  const [year, month] = period.split('-').map(Number);

  return new Intl.DateTimeFormat(language === 'bn' ? 'bn-BD' : 'en-US', {
    month: 'long',
    year: 'numeric',
    timeZone: 'UTC',
  }).format(new Date(Date.UTC(year, month - 1, 1)));
};

const getItemLabel = (
  key: string,
  fallback: string,
  language: ReceiptLanguage,
) => (language === 'bn' ? (bengaliItemLabels[key] ?? fallback) : fallback);

type Props = {
  bill: RentBill;
  language?: ReceiptLanguage;
};

export default function RentBillReceipt({
  bill,
  language = 'bn',
}: Props) {
  const text = copy[language];

  return (
    <article
      id="rent-bill-print-area"
      lang={language}
      className={`mx-auto w-full max-w-3xl bg-white p-6 text-slate-900 sm:p-9 ${
        language === 'bn' ? 'rent-bill-bengali' : ''
      }`}
    >
      <header className="flex items-start justify-between gap-6 border-b-2 border-slate-900 pb-5">
        <div className="flex items-center gap-4">
          <div className="relative h-14 w-28 shrink-0">
            <Image
              src="/logo.png"
              alt="AHB Home Management System"
              fill
              sizes="112px"
              className="object-contain object-left"
            />
          </div>
          <div>
            <h1 className="text-xl font-bold">{text.title}</h1>
            <p className="mt-1 text-sm text-slate-500">
              {formatMonth(bill.billingPeriod, language)}
            </p>
          </div>
        </div>

        <div className="text-right">
          <span
            className={`inline-flex rounded-md border-2 px-4 py-1 text-sm font-black ${
              language === 'en' ? 'tracking-[0.2em]' : ''
            } ${
              bill.status === 'paid'
                ? 'rotate-[-4deg] border-emerald-600 text-emerald-700'
                : bill.status === 'void'
                  ? 'border-slate-500 text-slate-500'
                  : 'rotate-[-4deg] border-red-600 text-red-700'
            }`}
          >
            {text.statuses[bill.status]}
          </span>
          <p className="mt-3 text-xs text-slate-500">{text.receiptNumber}</p>
          <p className="font-mono text-sm font-semibold">
            {bill.receiptNumber}
          </p>
        </div>
      </header>

      <section className="mt-6 grid gap-5 text-sm sm:grid-cols-2">
        <div>
          <p className="text-xs font-semibold uppercase tracking-wider text-slate-400">
            {text.billedTo}
          </p>
          <p className="mt-2 font-bold">{bill.tenantSnapshot.name}</p>
          <p className="mt-1 text-slate-600">{bill.tenantSnapshot.email}</p>
          {bill.tenantSnapshot.phone && (
            <p className="mt-1 text-slate-600">{bill.tenantSnapshot.phone}</p>
          )}
        </div>

        <div className="sm:text-right">
          <p className="text-xs font-semibold uppercase tracking-wider text-slate-400">
            {text.property}
          </p>
          <p className="mt-2 font-bold">
            {bill.propertySnapshot.name} /{' '}
            {bill.apartmentSnapshot.apartmentNumber}
          </p>
          <p className="mt-1 text-slate-600">
            {bill.propertySnapshot.address}
          </p>
        </div>
      </section>

      <section className="mt-6 overflow-hidden rounded-lg border border-slate-300">
        <table className="w-full text-sm">
          <thead className="bg-slate-100 text-left text-xs uppercase tracking-wider text-slate-500">
            <tr>
              <th className="px-4 py-3">{text.description}</th>
              <th className="px-4 py-3 text-right">{text.amount}</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-200">
            {bill.items.map((item) => (
              <tr key={`${item.key}-${item.label}`}>
                <td className="px-4 py-3">
                  {getItemLabel(item.key, item.label, language)}
                </td>
                <td className="px-4 py-3 text-right font-medium">
                  {item.amount === null ? '' : formatMoney(item.amount, language)}
                </td>
              </tr>
            ))}
          </tbody>
          <tfoot className="border-t-2 border-slate-300">
            <tr>
              <td className="px-4 py-2 text-right text-slate-500">
                {text.subtotal}
              </td>
              <td className="px-4 py-2 text-right font-semibold">
                {formatMoney(bill.subtotal, language)}
              </td>
            </tr>
            {bill.adjustmentAmount !== 0 && (
              <tr>
                <td className="px-4 py-2 text-right text-slate-500">
                  {text.adjustment}
                  {bill.adjustmentNote ? ` — ${bill.adjustmentNote}` : ''}
                </td>
                <td className="px-4 py-2 text-right font-semibold">
                  {formatMoney(bill.adjustmentAmount, language)}
                </td>
              </tr>
            )}
            <tr className="bg-slate-900 text-white">
              <td className="px-4 py-3 text-right font-bold">
                {text.grandTotal}
              </td>
              <td className="px-4 py-3 text-right text-lg font-black">
                {formatMoney(bill.totalAmount, language)}
              </td>
            </tr>
          </tfoot>
        </table>
      </section>

      <section className="mt-6 grid gap-4 text-sm sm:grid-cols-3">
        <Info
          label={text.issued}
          value={formatDate(bill.issuedAt, language)}
        />
        <Info
          label={text.dueDate}
          value={formatDate(bill.dueDate, language)}
        />
        <Info
          label={text.paidDate}
          value={
            bill.status === 'paid'
              ? formatDate(bill.paidAt, language)
              : text.unpaid
          }
        />
      </section>

      {bill.submeterReading && <section className="mt-5 rounded-xl border border-slate-300 p-4 text-xs text-slate-700">
        <p className="font-bold">{language === 'bn' ? 'সাবমিটার হিসাব' : 'Submeter calculation'} · {bill.submeterReading.meterNumber}</p>
        <p className="mt-2">{bill.submeterReading.currentReadingDate || '—'}: {bill.submeterReading.currentReading} − {bill.submeterReading.previousReadingDate || '—'}: {bill.submeterReading.previousReading} = {bill.submeterReading.consumedUnit} {language === 'bn' ? 'ইউনিট' : 'units'}</p>
        <p className="mt-2">{bill.submeterReading.calculation.tariff.name} · VAT {bill.submeterReading.calculation.tariff.vatPercentage}% · {formatMoney(bill.submeterReading.calculation.totalAmount, language)}</p>
      </section>}

      {(bill.note || bill.paymentNote) && (
        <section className="mt-6 rounded-lg bg-slate-100 p-4 text-sm">
          {bill.note && <p>{bill.note}</p>}
          {bill.paymentNote && (
            <p className={bill.note ? 'mt-2' : ''}>
              {text.paymentNote}: {bill.paymentNote}
            </p>
          )}
        </section>
      )}

      <footer className="mt-9 flex items-end justify-between gap-6 border-t border-slate-300 pt-5 text-xs text-slate-500">
        <div>
          <p className="font-semibold text-slate-700">
            {bill.ownerSnapshot.name}
          </p>
          {bill.ownerSnapshot.phone && <p>{bill.ownerSnapshot.phone}</p>}
        </div>
        <p className="text-right">{text.generatedBy}</p>
      </footer>
    </article>
  );
}

function Info({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-lg border border-slate-200 p-3">
      <p className="text-xs uppercase tracking-wider text-slate-400">{label}</p>
      <p className="mt-1 font-semibold text-slate-800">{value}</p>
    </div>
  );
}
